# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: Koslicki Lab # title of site, used in tab name and elsewhere
email: dmk333@psu.edu # default email
phone: 814-865-1611
location: W205 Westgate Building, University Park, PA 16802
google: Oz90sQsAAAAJ # default name to search on Google Scholar
github: KoslickiLab # default GitHub user/org, without the @
twitter: "" # default Twitter handle, without the @
instagram: "" # default Instagram handle, without the @
youtube: "channel/UC4ocxPwjndh1c9xr0HyD27Q" # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: "/Koslicki-lab-PSU"

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: Where (meta)genomes get compiled # description that will show under search engine results
      background: images/backgrounds/penn_state_bk.jpeg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
