name: Auto Cite

on:
  push:
    branches:
      - master
      - main
      - shaopeng_edit_publication
    paths:
      - "_data/research-input.yml"
  pull_request:
    paths:
      - "_data/research-input.yml"

jobs:
  update_research:
    name: Auto Cite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Manubot
        run: pip install --upgrade manubot
      - name: Build updated citations
        run: python _data/build-research.py
      - name: Commit updated citations
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "_data/research-output.yaml"
          commit_message: "Generate citations"
          push_options: --force
